### ISSUE TITLE
About usage in org-mode and nested directory

### ISSUE THREAD

**Issue by wztdream** [saf-dmitry/latex-math-input#1]
Hi,
I am looking for snippet for math in org-mode, great job.

Here are some questions, hope you can help:

1. It seems yasnippet does no support nested directory, but in this repo the snippet are in nested directory, so how to use it?
2. Any idea how to use it in org-mode, it seems there is an `texmathp` condition in all snippets, which is not compatible with org-mode

**Comment by saf-dmitry** [comment]
1. YASnippet _does support_ nested directories. I added installation instructions to the README. Basically, you just need to copy the _content_ of the `yasnippets` folder to one of the directories specified in the `yas-snippet-dirs` variable.

2. Most snippets, except for math environment delimiters like the `equation` environment, have the `condition` field set to `(yas-texmathp)`. The latter is intended to control expansion depending on the local context. You can define it as you see fit. For example, to allow snippet expansion everywhere for Org mode only, you may add following to your Emacs config file:

    ```elisp
    (defun yas-texmathp ()
      (if (derived-mode-p 'org-mode)
          t
        (require 'texmathp) (texmathp)))
    ```

P.S. Don't forget to add `latex-mode` to the `.yas-parents` file in the `org-mode` snippet sub-directory as described in the [YASnippets documentation](http://joaotavora.github.io/yasnippet/snippet-organization.html).

**Comment by wztdream** [comment]
Thank you for your detail explain, it now work like a charm :)
